Tracking/Tracking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base_app.urls')),
]

if settings.DEBUG:
    if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tracking/base_app/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

# Create your models here.


class Client(models.Model):
    objects = None
    name = models.CharField(max_length=100, verbose_name='Имя клиента')
    email = models.EmailField(verbose_name='Email')
    phone = models.CharField(max_length=15, verbose_name='Телефон')
    photo = models.ImageField(upload_to='images',
                              help_text="Введите фото",
                              verbose_name="Фото клиента",
                              null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Order(models.Model):
    objects = None
    order_number = models.CharField(max_length=100, verbose_name='Номер заказа')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='orders', verbose_name='Клиент')
    product = models.CharField(max_length=100, verbose_name="Товар")
    CATEGORY_CHOICES = [
        ('Процессоры', 'Процессоры'),
        ('Материнские платы', 'Материнские платы'),
        ('Видеокарты', 'Видеокарты'),
        ('Оперативная память', 'Оперативная память'),
        ('SSD-диски', 'SSD-диски'),
        ('HDD-диски', 'HDD-диски'),
        ('Блоки питания>', 'Блоки питания'),
    ]
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, verbose_name='Категория')
    photo = models.ImageField(upload_to='images',
                              help_text="Введите фото",
                              verbose_name="Фото товара",
                              null=True, blank=True)
    
    order_date = models.DateField(verbose_name='Дата заказа')
    order_amount = models.DecimalField(verbose_name="Сумма заказа", max_digits=10, decimal_places=2)
    ORDER_STATUS_CHOICES = [
        ('Поступил', 'Поступил'),
        ('Выполняется', 'Выполняется'),
        ('Закрыт', 'Закрыт'),
    ]
    status = models.CharField(max_length=50, choices=ORDER_STATUS_CHOICES, verbose_name='Статус')
    completed = models.BooleanField(default=False, verbose_name='Заказ завершен')
    completion_date = models.DateField(null=True, blank=True, verbose_name='Дата завершения')


    def __str__(self):
        return f'{self.order_number} {self.client}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


@receiver(pre_save, sender=Order)
def update_completion_date(sender, instance, **kwargs):
    if instance.completed and not instance.completion_date:
        instance.completion_date = instance.date_created        

Tracking/templates/add_client.html
{% extends 'base.html' %}

{% block title  %} 
Добавление клиента 
{% endblock  %}


{% block content %}
<br>

<div class="header-bar">
    <div>
        <br>
        <h1>Hello {{ request.user|title }}</h1>        
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>

<br><br>
<h4> {{ header }}</h4>
<div class="container">
    <form method="POST">
        {% csrf_token %} 

        {%  for field in form  %}
        <div class="form group">
            <label for="id_{{ field.name }}" class="col-2 col-form-label">{{ field.label }}</label>
            <div class="col-10">
                {{ field }}
            </div>
        </div>
        {%  endfor %}

        <div class="button-container">
            <button type="submit" class="btn btn-primary" name="button">Добавить</button>
            <a href="{% url 'client_list' %}" class="btn btn-secondary">Назад </a>
        </div>        
    </form>
</div>
{% endblock content %}

Tracking/templates/add_order.html
{% extends 'base.html' %}

{% block title %} Добавить заказ  {% endblock %}

{% block content %}
<br>

<div class="header-bar">
    <div>
        <br>
        <h1>Hello {{ request.user|title }}</h1>        
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>

<br><br>
<h4> {{ header }}</h4>
<div class="container">
    <form method="POST">
        {% csrf_token %} 

        {%  for field in form  %}
        <div class="form group">
            <label for="id_{{ field.order_number }}" class="col-2 col-form-label">{{ field.label }}</label>
            <div class="col-10">
                {{ field }}
            </div>
        </div>
        {%  endfor %}

        <div class="button-container">
            <button type="submit" class="btn btn-primary" name="button">Добавить</button>
            <a href="{% url 'order_list' %}" class="btn btn-secondary">Назад </a>
        </div>        
    </form>
</div>
{% endblock %}

Tracking/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %} </title>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ИС отслеживания клиентов и заказов</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarsExample02">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Главная</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'client_list' %}">Клиенты</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'order_list' %}">Заказы</a>
              </li>
              <li class="nav-item">
                 <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Админ панель</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
            </ul>
            <form>
              <input class="form-control" type="text" placeholder="Search" aria-label="Search">
            </form>
          </div>
        </div>
      </nav>

      <div class="container">
        {% block content %}

        {% endblock content %}
      </div>
    <script src="{% static '/js/bootstrap.min.js' %}"  ></script>
    <footer class="container">
        <p>© 2024 <img src="{% static 'images/logo.jpg' %}" alt="My Company" width="100px" height="100px"> Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
     </footer>
</body>
</html>

Tracking/templates/client_detail.html
{% extends 'base.html' %}

{% block title %}
Информация о клиентах 
{% endblock %}

{% block content %}
<br>
<div class="header-bar">
    <div>
        <br>
        <h1>Hello {{ request.user|title }}</h1>        
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>

<div class="container mt-5">
    <h1 class="text-center">Информация о клиентах</h1>
    <div class="alert alert-info">
        <div class="row">
            <div class="col">
                <h4>Имя клиента:</h4>
                <p> {{ client.name }}</p>
            </div>
            <div class="col">
                <h4>Электронная почта:":</h4>
                <p> {{ client.email }}</p>
            </div>
            <div class="col">
                <h4>Телефон:</h4>
                <p> {{ client.phone }}</p>
             </div>           
            <div class="col">
                <h4>Фото:</h4>
                <p> <img src="{{ client.photo.url }}" alt="connect"
                                 style="max-height:100px">
                </p>
                <p><a href="{{ client.photo.url}}"
                       class="btn btn-primary"
                       target="_blank"> Показать</a></p>
             </div>
        </div>        
        <a href="{% url 'display_clients' %}" class="btn btn-warning" role="button">К клиентам </a>
        <a href="{% url 'edit_client' client.pk %}" class="btn btn-primary">Редактировать</a>
        <a href="{% url 'delete_client' client.pk %}" class="btn btn-warning" role="button">Удалить</a>
    </div>
</div> 
{% endblock %}

Tracking/templates/client_list.html
{% extends 'base.html' %}

{% block title  %}  Клиенты {% endblock  %}

{% block content %}
<br>
<div class="header-bar">
    <div>
        <br>
        <h1>Hello {{ request.user|title }}</h1>        
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>

<br> 
<div class="row text-center text-dark lh-2">
    <h4>Список клиентов в БД</h4>
</div>
<div class="button-group">
    <a href="{% url 'display_clients' %}" class="btn btn-primary btn-end" role="button">Клиенты</a>
    <a href="{% url 'display_orders' %}" class="btn btn-primary btn-end" role="button">К заказам</a>
    <a href="{% url 'add_client' %}" class="btn btn-warning btn-sm" role="button"> +</a>
    <a href="{% url 'print_clients' %}" class="btn btn-info btn-sm" onclick="window.print();">Печать</a>
</div>

<br>
<h4>Currently, Viewing {{ header }}</h4>
<!-- Форма поиска по наименованию клиента -->
<form action="{% url 'search_clients' %}" method="GET">
    <input type="text" name="name" placeholder="Search by name">
    <div class="button-container">
        <button type="submit" class="btn btn-primary" name="button">Поиск клиентов</button>
        <a href="{% url 'display_clients' %}" class="btn btn-secondary" role="button">Перезагрузка</a>
    </div>
</form>
<br>
<table class="table table-hover">
    <thead>
        <tr>
            <th>ИД</th>
            <th>Клиент</th>
            <th>Электронная почта</th>
            <th>Телефон</th>
            <th>Показать фото</th>
            <th></th>            
            <th>Детали</th>
        </tr>
    </thead>
    <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.pk }}</td>
                <td>{{ client.name }}</td>
                <td>{{ client.email }}</td>
                <td>{{ client.phone }}</td>
                
                <td>
                    <img src="{{ client.photo.url }}" alt="connect"
                                 style="max-height:100px">
                </td>
                <td>
                    <a href="{{ client.photo.url}}"
                       class="btn btn-primary"
                       target="_blank"> Показать</a>
                </td>
                <td>
                    <a href="{% url 'client_detail' client.pk %}" class="btn btn-warning btn-sm" role="button"> Детали</a>
                </td>
            </tr>
        {% endfor %}        
    </tbody>
</table>

{% endblock content %}

Tracking/templates/edit_client.html
{% extends 'base.html' %}

{% block title  %} 
Редактирование клиента 
{% endblock  %}


{% block content %}
<br>

<div class="header-bar">
    <div>
        <br>
        <h1>Hello {{ request.user|title }}</h1>        
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>

<br><br>
<h4> {{ header }}</h4>
<div class="container">
    <form method="POST">
        {% csrf_token %} 

        {%  for field in form  %}
        <div class="form group">
            <label for="id_{{ field.name }}" class="col-2 col-form-label">{{ field.label }}</label>
            <div class="col-10">
                {{ field }}
            </div>
        </div>
        {%  endfor %}

        <div class="button-container">
            <button type="submit" class="btn btn-primary" name="button">Редактировать</button>
            <a href="{% url 'client_list' %}" class="btn btn-secondary">Назад </a>
        </div>        
    </form>
</div>
{% endblock content %}

Tracking/templates/edit_order.html
{% extends 'base.html' %}

{% block title %} Редактировать заказ  {% endblock %}

{% block content %}
<br>

<div class="header-bar">
    <div>
        <br>
        <h1>Hello {{ request.user|title }}</h1>        
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>

<br><br>
<h4> {{ header }}</h4>
<div class="container">
    <form method="POST">
        {% csrf_token %} 

        {%  for field in form  %}
        <div class="form group">
            <label for="id_{{ field.order_number }}" class="col-2 col-form-label">{{ field.label }}</label>
            <div class="col-10">
                {{ field }}
            </div>
        </div>
        {%  endfor %}

        <div class="button-container">
            <button type="submit" class="btn btn-primary" name="button">Редактировать</button>
            <a href="{% url 'order_list' %}" class="btn btn-secondary">Назад </a>
        </div>        
    </form>
</div>
{% endblock %}

Tracking/templates/index.html
{% extends 'base.html' %}

{% block title %}
Главная страница сайта
{% endblock %}

{% block content %}

<br>

<div class="header-bar">
    <div>
        <br>
        <h1>Hello {{ request.user|title }}</h1>        
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-12">                  
            <img src="https://overclockers.ru/st/legacy/blog/378660/482614_O.png" class="img-fluid resized-image" alt="Компьютерный магазин">
        </div>
    </div>
</div>
{% endblock %}

Tracking/templates/login.html
{% extends 'base.html' %}
{% block content  %}

<br>

<div class="header-bar">
    <h1>Login</h1>
</div>
<div class="card-body">
    <form method="post">
        {% csrf_token %}
        <label class="form-group">{{ form.username.label }}</label>
        {{ form.username }}

        <label class="form-group">{{ form.password.label }}</label>
        {{ form.password }}
   
        <div class="button-container">
            <input class="button" type="submit" value="Login">
        </div>
    </form>
    <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
</div>

{% endblock content  %}

Tracking/templates/order_detail.html
{% extends 'base.html' %}

{% block title %}
Информация о заказе
{% endblock %}

{% block content %}
<br>
<div class="header-bar">
    <div>
        <br>
        <h1>Hello {{ request.user|title }}</h1>        
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>

<div class="container mt-5">
    <h1 class="text-center">Информация о заказе</h1>
    <div class="alert alert-info">
        <div class="row">
            <div class="col">
                <h4>Номер заказа:</h4>
                <p> {{ order.order_number }}</p>
            </div>
            <div class="col">
                <h4>Клиент:</h4>
                <p> {{ order.client.name }}</p>
            </div>
            <div class="col">
                <h4>Товар:</h4>
                <p> {{ order.product }}</p>
            </div>
            <div class="col">
                <h4>Категория:</h4>
                <p> {{ order.get_category_display }}</p>
            </div>
            <div class="col">
                <h4>Фото:</h4>
                <p> <img src="{{ order.photo.url }}" alt="connect"
                                 style="max-height:100px">
                </p>
                <p><a href="{{ order.photo.url}}"
                       class="btn btn-primary"
                       target="_blank"> Показать</a></p>
             </div>
            <div class="col">
                <h4>Дата заказа:</h4>
                <p> {{ order.order_date }}</p>
            </div>
            <div class="col">
                <h4>Сумма заказа:</h4>
                <p> {{ order.order_amount }}</p>
            </div>
            <div class="col">
                <h4>Статус:</h4>
                <p> {{ order.get_status_display }}</p>
            </div>
            <div class="col">
                <h4>Заказ завершен:</h4>
                <p> {{ order.completed }}</p>
            </div>
            <div class="col">
                <h4>Дата завершения:</h4>
                <p> {{ order.completion_date }}</p>
            </div>
        </div>        
        <a href="{% url 'display_orders' %}" class="btn btn-warning" role="button">К заказам </a>
        <a href="{% url 'edit_order' order.pk %}" class="btn btn-primary">Редактировать</a>
        <a href="{% url 'delete_order' order.pk %}" class="btn btn-warning" role="button">Удалить</a>
    </div>
</div> 
{% endblock %}

Tracking/templates/order_list.html
{% extends 'base.html' %}

{% block title  %}  Заказы {% endblock  %}

{% block content %}
<br>
<div class="header-bar">
    <div>
        <br>
        <h1>Hello {{ request.user|title }}</h1>        
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>

<br> 
<div class="row text-center text-dark lh-2">
    <h4>Список заказов в БД</h4>
</div>
<br>
<div class="button-group">
    <a href="{% url 'display_orders' %}" class="btn btn-primary btn-end" role="button">Заказы</a>
    <a href="{% url 'display_clients' %}" class="btn btn-warning" role="button">К клиентам</a>
    <a href="{% url 'add_order' %}" class="btn btn-warning btn-sm" role="button"> +</a>
    <a href="{% url 'print_orders' %}" class="btn btn-info btn-sm" onclick="window.print();">Печать</a>
</div>

<br>
<h4>Currently, Viewing {{ header }}</h4>
<!-- Форма поиска заказа по наименованию товара -->
<form action="{% url 'search_orders' %}" method="GET">
    <input type="text" name="client" placeholder="Search by client">
    <div class="button-container">
        <button type="submit" class="btn btn-primary" name="button">Поиск заказов</button>
        <a href="{% url 'display_orders' %}" class="btn btn-secondary" role="button">Перезагрузка</a>        
    </div>
</form><br>
<br>
{% if orders %}
    <table class="table table-dark table-hover table-striped table-bordered text-start">
            <thead>
                <tr>
                    <th>ИД</th>
                    <th>Номер заказа</th>
                    <th>Клиент</th>
                    <th>Товар</th>
                    <th>Категория</th>
                    <th>Фото</th>                                                           
                    <th>Дата заказа</th>
                    <th>Сумма заказа</th>
                    <th>Статус</th>
                    <th>Отметка о выполнении</th>
                    <th>Дата выполнения</th>    
                    <th>Детали</th>                
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <td>{{ order.pk }}</td>
                        <td>{{ order.order_number }}</td>
                        <td>{{ order.client.name }}</td>
                        <td>{{ order.product }}</td>
                        <td>{{ order.category }}</td>
                        <td>
                            {% if order.photo %}
                                <img src="{{ order.photo.url }}" alt="connect" style="max-height:100px">
                                <a href="{{ order.photo.url }}" class="btn btn-primary" target="_blank">Показать</a>
                            {% else %}
                                Фото отсутствует
                            {% endif %}
                        </td>
                        <td>{{ order.order_date }}</td>
                        <td>{{ order.order_amount }}</td>
                        <td>{{ order.status }}</td>
                        <td>{{ order.completed }}</td>
                        <td>{{ order.completion_date }}</td>                        
                        <td>
                            <a href="{% url 'order_detail' order.pk %}" class="btn btn-warning btn-sm" role="button"> Детали</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
      <p>В базе данных нет заказов </p>
    {% endif %}
    {% if graph_base64 %}
        <img src="data:image/png;base64,{{ graph_base64 }}" alt="Orders Statistics">
    {% endif %}

{% endblock content %}

Tracking/templates/register.html
{% extends 'base.html' %}
{% block content  %}

<br>

<div class="header-bar">
    <h1>Register</h1>
</div>
<div class="card-body">
    <form method="post">
        {% csrf_token %}
        <label class="form-group">{{form.username.label}}</label>
        {{form.username}}

        <label class="form-group">{{form.password1.label}}</label>
        {{form.password1}}

         <label class="form-group">{{form.password2.label}}</label>
        {{form.password2}}

        <div class="button-container">
            <input class="button" type="submit" value="Register">
        </div>
    </form>
    <p>Already have an account? <a href="{% url 'login' %}">Login</a> </p>
</div>

{% endblock content  %}